const Map<String, int> vidaUtilPorCategoria = {
  'verdura':     7,
  'fruta':       7,
  'hierba':      5,
  'carne':       3,
  'pollo':       3,
  'pescado':     2,
  'huevo':       21,
  'leche':       8,
  'yogur':       14,
  'queso':       21,
  'mantequilla': 30,
  'pan':         5,
  'embutido':    7,
  'jugo':        7,
  'grano':       365,
  'conserva':    365,
  'cereal':      180,
  'otro':        7,
};